version: '2'
services:
    openldap:
        image: osixia/openldap
        environment:
            LDAP_LOG_LEVEL: "256"
            LDAP_ORGANISATION: "Exército Brasileiro"
            LDAP_DOMAIN: "eb.mil.br"
            LDAP_BASE_DN: ""
            LDAP_ADMIN_PASSWORD: "admin"
            LDAP_CONFIG_PASSWORD: "config"
            LDAP_READONLY_USER: "true"
            LDAP_READONLY_USER_USERNAME: "readonly"
            LDAP_READONLY_USER_PASSWORD: "readonly"
            LDAP_RFC2307BIS_SCHEMA: "false"
            LDAP_BACKEND: "mdb"
            LDAP_TLS: "false"
            #      LDAP_TLS_CRT_FILENAME: "ldap.crt"
            #      LDAP_TLS_KEY_FILENAME: "ldap.key"
            #      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
            #      LDAP_TLS_ENFORCE: "false"
            #      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
            #      LDAP_TLS_PROTOCOL_MIN: "3.1"
            #      LDAP_TLS_VERIFY_CLIENT: "demand"
            LDAP_REPLICATION: "false"
            #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
            #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
            #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
            KEEP_EXISTING_CONFIG: "false"
            LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
            LDAP_SSL_HELPER_PREFIX: "ldap"
        tty: true
        stdin_open: true
        #    volumes:
        #      - /var/lib/ldap
        #      - /etc/ldap/slapd.d
        #      - /container/service/slapd/assets/certs/
        ports:
            - "8389:389"
            - "8636:636"
        domainname: "eb.mil.br" # important: same as hostname
        hostname: "eb.mil.br"
        networks:
            - sso-net
        volumes:
            - /data/slapd/database:/var/lib/ldap
            - /data/slapd/config:/etc/ldap/slapd.d

    phpldapadmin:
        image: osixia/phpldapadmin
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: "openldap"
            PHPLDAPADMIN_HTTPS: "false"
        ports:
        - "8980:80"
        depends_on:
        - openldap
        networks:
        - sso-net

    maildev:
        image: maildev/maildev
        ports:
        - "1080:80"
        - "1025:25"
        networks:
        - sso-net

    redis:
        image: redis:4.0.9-alpine
        ports:
        - "6379:6379"
        networks:
        - sso-net



networks:
    sso-net:
